### ISSUE TITLE
[Pavlov]: Bug report

### ISSUE THREAD

**Issue by Blitx** [fholger/openvr_foveated#3]
**Which game is affected?**
Pavlov

**Describe the issue**
Foveated rendering functions as intended for the first 10 or so seconds, then anything outside of the first ring turns white. 

**Hardware**
HTC Vive
RX 6700XT

**Config and log**
[openvr_mod.zip](https://github.com/fholger/openvr_foveated/files/7768436/openvr_mod.zip)

**Comment by fholger** [comment]
Does the game have graphics settings you can experiment with? Specifically, if it has any anti-aliasing options, try to switch to a different anti-aliasing method or disable it altogether. Also try to disable any kind of post-processing effect (like Bloom).

**Comment by Blitx** [comment]
The only video settings in menu are Render Scale, from 100% to 0%. Antialias, Textures, and Effects have four settings; Ultra, High, Medium, and Low. Changing them doesn't fix the white ring.

It seems the game doesn't like being launched with AA on low. Launching with AA on any other setting works fine, but it appears that changing AA setting doesn't actually change anything until next launch.

### Solution
Start Pavlov with AA set to medium or higher.

**Comment by fholger** [comment]
Great! Mind adding an entry in the Wiki about your findings? :)

**Comment by Blitx** [comment]
> Great! Mind adding an entry in the Wiki about your findings? :)

I don't think I can if I'm not a contributor, but I'll save you the time of writing an entry out.

⚠️Pavlov

- Engine: Unreal
- DLL path: steamapps\common\PavlovVR\Engine\Binaries\ThirdParty\OpenVR\OpenVRv1_0_16\Win64
- Works?: Yes.
- Notes: Start the game with Antialiasing at Medium or higher.
- Tested version: v0.1

**Comment by fholger** [comment]
Oh sorry, I forgot to make the Wiki public. Anyway, I added the entry, thanks.
