### ISSUE TITLE
[Question] Dynamic foveated rendering with eye tracking?

### ISSUE THREAD

**Issue by bipul-mohanto** [fholger/openvr_foveated#9]
Do you have any plan including the built-in eye tracker for dynamic foveated rendering? That might help people observing flicker.

**Comment by fholger** [comment]
I don't have any eye-tracking hardware currently, and even if, dynamic foveated rendering is probably a bit more complicated than just moving the center around. So probably no.

**Comment by bipul-mohanto** [comment]
I will have Tobii Eye tracker 5 soon. Probably I will give a try to further develop your repository.
